application: gomytrack
version: dev
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: markupsafe
  version: latest

handlers:
- url: /static
  static_dir : app/static
- url: .*
  script: main.app
